### PR TITLE
Bumped galen version

### PR DESCRIPTION
**Pull request by mrlove**
We need the new version for our project

### CODE REVIEW

**Comment by ishubin** [comment]
I am not sure how it all works as this was repo configured by @whitneyit 

@whitneyit aren't we supposed also to build an appropriate jar and put it in here when we update the version?

**Comment by whitneyit** [comment]
This repo is supposed to be updated inline with jar releases. I'll get
right on it. I've been very busy and these tasks fell off of my radar.
Thanks for brining it back to my attention :)

**Comment by ishubin** [comment]
@whitneyit thanks! I will get back to you when I will release galen version 2.0. Hope I can also maintain this repo if needed

**Comment by whitneyit** [comment]
I remember wanting to work on using node to deploy versioned changes. I'll update [`galen-cli`](https://github.com/whitneyit/galen-cli) as well

**Comment by whitneyit** [comment]
I imagine the following workflow

```sh
$ npm install --global galen-cli
```

Then in your project

```sh
$ npm install --save-dev galen # Can't be done due to the name being already in use
```

Then we just use the `galen` package that has a dependency on the `galen-jar`.

**Comment by whitneyit** [comment]
This how now been merged

**Pull request closed without merging**
